- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.3
  hooks:
  - id: autopep8-wrapper
  - id: trailing-whitespace
  - id: flake8
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: ['--autofix']
- repo: git://github.com/FalconSocial/pre-commit-python-sorter
  sha: b57843b0b874df1d16eb0bef00b868792cb245c2
  hooks:
  - id: python-import-sorter
    args: ['--silent-overwrite']
- repo: https://github.com/asottile/add-trailing-comma
  sha: v0.6.4
  hooks:
  - id: add-trailing-comma
